### PR TITLE
bug: fix pinned pydantic dependency

### PR DESCRIPTION
**Pull request by mgorsk1**

### CODE REVIEW

**Comment by mgorsk1** [comment]
cc @verdan would you mind approving and releasing this? this hard pin is biting us in the a** :P

**Comment by verdan** [comment]
I thought we were already using `https://pypi.org/project/apache-atlas/`, as this repository is not being maintained anymore.

**Comment by mgorsk1** [comment]
the migration to official atlas client did not cover 100% of amundsen code and there are places where it's still used (in databuilder)

**Comment by verdan** [comment]
@mgorsk1 https://pypi.org/project/pyatlasclient/1.2.0/

**Pull request merged**
